// Zitate-Sammlung für die Impulse-Seite.
// Jeder Eintrag: { text, author, category }
// Kategorien werden automatisch zu Filter-Chips auf /impulse.

window.QUOTES = [

  // ---------- Liebe (17) ----------
  { text: "Die Liebe will nichts von dem anderen, sie will alles für den anderen.", author: "Dietrich Bonhoeffer", category: "Liebe" },
  { text: "Gottes Liebe brauchen wir nicht von uns aus zu produzieren, sondern lediglich von ihm aus zu reflektieren.", author: "Hans-Joachim Eckstein", category: "Liebe" },
  { text: "Es ist einfacher, einen hungrigen Bauch zu füllen als ein leeres Herz.", author: "Mutter Teresa", category: "Liebe" },
  { text: "Wir werden geboren mit der Fähigkeit zu lieben. Alles andere ist optional.", author: "Isabelle Huppert", category: "Liebe" },
  { text: "Es gibt keine Liebe, es gibt nur Beweise von Liebe.", author: "Pierre Reverdy", category: "Liebe" },
  { text: "Die Liebe besteht nicht darin, einander anzusehen, sondern gemeinsam in die gleiche Richtung zu blicken.", author: "Antoine de Saint-Exupéry", category: "Liebe" },
  { text: "Liebe ist nicht, jemanden zu finden, der perfekt ist. Liebe ist, jemanden perfekt unvollkommen zu sehen.", author: "Sam Keen", category: "Liebe" },
  { text: "Lieben heißt, sich selbst an den anderen verschenken, ohne etwas verlieren zu können.", author: "Rainer Maria Rilke", category: "Liebe" },
  { text: "Wer liebt, der sieht den anderen nicht so, wie er ist — sondern so, wie er sein könnte.", author: "Goethe", category: "Liebe" },
  { text: "Ich habe dich lieb — nicht wegen dem, was du bist, sondern wegen dem, was ich bin, wenn ich mit dir zusammen bin.", author: "Roy Croft", category: "Liebe" },
  { text: "Was man aus Liebe tut, geschieht immer jenseits von gut und böse.", author: "Friedrich Nietzsche", category: "Liebe" },
  { text: "Verliebt sein ist ein Zustand. Liebe ist eine Entscheidung.", author: null, category: "Liebe" },
  { text: "Man sieht nur mit dem Herzen gut. Das Wesentliche ist für die Augen unsichtbar.", author: "Antoine de Saint-Exupéry", category: "Liebe" },
  { text: "Im Leben geht es nicht darum, sich selbst zu finden. Es geht darum, sich selbst zu erschaffen.", author: "George Bernard Shaw", category: "Liebe" },
  { text: "Liebe ist der einzige Reichtum, der größer wird, wenn man ihn verschenkt.", author: null, category: "Liebe" },
  { text: "Der einzige Weg, einen Freund zu haben, ist, einer zu sein.", author: "Ralph Waldo Emerson", category: "Liebe" },
  { text: "Trotz allem glaube ich an das Gute im Menschen.", author: "Anne Frank", category: "Liebe" },

  // ---------- Begegnung (18) ----------
  { text: "Menschen sind wie Teebeutel: Man weiß nicht, was der Inhalt ist, bis sie im heißen Wasser sitzen.", author: "Leo Bigger", category: "Begegnung" },
  { text: "Wir sollten unser Holz nicht für höhere Zäune verwenden, sondern für längere Tische.", author: "Andreas Boppart", category: "Begegnung" },
  { text: "Jeder, den du triffst, kämpft einen Kampf, von dem du nichts weißt. Sei freundlich. Immer.", author: "Ian Maclaren", category: "Begegnung" },
  { text: "Aufmerksamkeit ist die seltenste und reinste Form der Großzügigkeit.", author: "Simone Weil", category: "Begegnung" },
  { text: "Eine gute Unterhaltung ist wie ein Miniröckchen: Kurz genug, um interessant zu sein, lang genug, um das Wesentliche zu bedecken.", author: "Henry Kissinger", category: "Begegnung" },
  { text: "Die meisten Menschen hören nicht zu, um zu verstehen. Sie hören zu, um zu antworten.", author: "Stephen R. Covey", category: "Begegnung" },
  { text: "Vertrauen wächst, wenn Menschen mehr versprechen, als sie halten müssen — und dann auch halten.", author: null, category: "Begegnung" },
  { text: "Wenn du etwas lernen willst, hör auf zu reden.", author: "Dalai Lama", category: "Begegnung" },
  { text: "Manche Menschen kommen in dein Leben und gehen wieder. Andere kommen für eine Weile und hinterlassen Fußspuren in deinem Herzen.", author: "Flavia Weedn", category: "Begegnung" },
  { text: "Menschen werden nicht dafür geliebt, wie sie sind, sondern dafür, wie sie uns fühlen lassen.", author: null, category: "Begegnung" },
  { text: "Die schwierigste Beziehung haben wir oft zu uns selbst.", author: "Pema Chödrön", category: "Begegnung" },
  { text: "Nähe ist, wenn zwei Menschen in denselben Sachen schweigen.", author: null, category: "Begegnung" },
  { text: "Freundschaft ist eine Seele in zwei Körpern.", author: "Aristoteles", category: "Begegnung" },
  { text: "Ein Freund ist ein Mensch, vor dem man laut denken kann.", author: "Ralph Waldo Emerson", category: "Begegnung" },
  { text: "Man kann mehr über einen Menschen in einer Stunde des Spiels lernen, als in einem Jahr des Gesprächs.", author: "Platon", category: "Begegnung" },
  { text: "Wer das erste Knopfloch verfehlt, kommt mit dem Zuknöpfen nicht zurecht.", author: "Johann Wolfgang von Goethe", category: "Begegnung" },
  { text: "Höre nicht, um zu antworten, sondern um zu verstehen.", author: "Stephen R. Covey", category: "Begegnung" },
  { text: "Die leiseste Stimme im Raum ist oft die weiseste.", author: null, category: "Begegnung" },

  // ---------- Wachstum (24) ----------
  { text: "Versuche nicht ein erfolgreicher, sondern ein wertvoller Mensch zu werden.", author: "Albert Einstein", category: "Wachstum" },
  { text: "Unser größter Ruhm ist nicht, niemals zu fallen, sondern jedes Mal wieder aufzustehen.", author: "Ralph Waldo Emerson", category: "Wachstum" },
  { text: "Disziplin ist nur die Wahl zwischen dem, was du jetzt willst und dem, was du am meisten willst.", author: null, category: "Wachstum" },
  { text: "You're never going to be perfect — there is no such thing. You're human. So instead, aim for progress, even the smallest amount.", author: "Ryan Holiday", category: "Wachstum" },
  { text: "Du musst Chaos in dir haben, um einen tanzenden Stern gebären zu können.", author: "Friedrich Nietzsche", category: "Wachstum" },
  { text: "Jeder Mensch ist mehr als er selber weiß.", author: "Hermann Hesse", category: "Wachstum" },
  { text: "Gestern war ich klug, also wollte ich die Welt verändern. Heute bin ich weise, also ändere ich mich selbst.", author: "Rumi", category: "Wachstum" },
  { text: "Zwischen Reiz und Reaktion liegt ein Raum. In diesem Raum liegt unsere Macht, unsere Antwort zu wählen.", author: "Viktor Frankl", category: "Wachstum" },
  { text: "Man muss das Unmögliche versuchen, um das Mögliche zu erreichen.", author: "Hermann Hesse", category: "Wachstum" },
  { text: "Wer sich selbst kennt, ist erleuchtet. Wer andere kennt, ist weise.", author: "Lao Tzu", category: "Wachstum" },
  { text: "Die Qualität deines Lebens wird durch die Qualität deiner Prinzipien bestimmt.", author: null, category: "Wachstum" },
  { text: "Ich bin nicht, was mir widerfahren ist. Ich bin, was ich mich entscheide zu werden.", author: "C. G. Jung", category: "Wachstum" },
  { text: "Es ist nicht genug zu wissen, man muss es auch anwenden. Es ist nicht genug zu wollen, man muss es auch tun.", author: "Goethe", category: "Wachstum" },
  { text: "Ein Baum wächst nicht in einem Tag. Aber jeden Tag wächst er ein Stück.", author: null, category: "Wachstum" },
  { text: "Wer nie in die Leitplanken geflogen ist, ist nie schnell gefahren.", author: "Mario Andretti", category: "Wachstum" },
  { text: "Fehler sind die Spuren, die der Mut hinterlässt.", author: null, category: "Wachstum" },
  { text: "Fall down seven times, stand up eight.", author: "Japanisches Sprichwort", category: "Wachstum" },
  { text: "Die Reise von tausend Meilen beginnt mit einem einzigen Schritt.", author: "Lao Tzu", category: "Wachstum" },
  { text: "Ich kann versagen. Ich kann nicht aufgeben.", author: "Michael Jordan", category: "Wachstum" },
  { text: "Erkenne dich selbst.", author: "Orakel von Delphi", category: "Wachstum" },
  { text: "Die meisten Menschen sterben mit ihrer Musik noch in sich.", author: "Oliver Wendell Holmes", category: "Wachstum" },
  { text: "Was man einmal geworden ist, kann man nicht ungeschehen machen.", author: "Milan Kundera", category: "Wachstum" },
  { text: "Ich bin nicht, was ich war. Ich bin nicht, was ich sein werde. Ich bin, was ich werde.", author: null, category: "Wachstum" },
  { text: "Wer aufhört besser zu werden, hat aufgehört gut zu sein.", author: "Oliver Cromwell", category: "Wachstum" },

  // ---------- Tiefe (19) ----------
  { text: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: null, category: "Tiefe" },
  { text: "Viele Dinge zu wissen bedeutet noch nicht, sie zu verstehen.", author: "Heraklit", category: "Tiefe" },
  { text: "Die Schönheit und Heiligkeit des Lebens erschließt sich in der Tiefe, nicht in der Vielzahl der Beschäftigungen.", author: "Johannes Hartl", category: "Tiefe" },
  { text: "Was du hast, können viele haben, doch was du bist, kann keiner sein.", author: null, category: "Tiefe" },
  { text: "Das äußere Glück ist nur von Zufall, aber das Innere baut sich ein jeder selbst.", author: "Matthias Claudius", category: "Tiefe" },
  { text: "Im tiefsten Winter erfuhr ich schließlich, dass in mir ein unbesiegbarer Sommer liegt.", author: "Albert Camus", category: "Tiefe" },
  { text: "Die Grenzen meiner Sprache bedeuten die Grenzen meiner Welt.", author: "Ludwig Wittgenstein", category: "Tiefe" },
  { text: "Es ist nicht das Dunkel in der Welt, was die Welt dunkel macht. Es ist, wie wir sie anschauen.", author: null, category: "Tiefe" },
  { text: "Am Grunde aller Dinge schläft ein Lied.", author: "Joseph von Eichendorff", category: "Tiefe" },
  { text: "Ein Buch muss die Axt sein für das gefrorene Meer in uns.", author: "Franz Kafka", category: "Tiefe" },
  { text: "Der Charakter ist das Schicksal des Menschen.", author: "Heraklit", category: "Tiefe" },
  { text: "Jeder Mensch trägt ein Zimmer in sich.", author: "Franz Kafka", category: "Tiefe" },
  { text: "In der Tiefe der Seele sind wir alle gleich einsam.", author: "Rainer Maria Rilke", category: "Tiefe" },
  { text: "Niemand ist jemals so allein, wie er glaubt. Oder so verstanden, wie er hofft.", author: null, category: "Tiefe" },
  { text: "Wer nach innen schaut, erwacht.", author: "Carl Gustav Jung", category: "Tiefe" },
  { text: "Im Grunde sind es doch die Verbindungen mit Menschen, die dem Leben seinen Wert geben.", author: "Wilhelm von Humboldt", category: "Tiefe" },
  { text: "Man muss still werden, um die Welt wieder hören zu können.", author: null, category: "Tiefe" },
  { text: "Das Herz hat Räume, von denen du nicht weißt, bis die Trauer dir den Schlüssel gibt.", author: null, category: "Tiefe" },
  { text: "Wer nichts mehr sagt, hat oft am meisten zu sagen.", author: null, category: "Tiefe" },

  // ---------- Stille (13) ----------
  { text: "Alles Unglück der Menschen rührt von einer einzigen Ursache: dass sie nicht ruhig in einem Zimmer sitzen können.", author: "Blaise Pascal", category: "Stille" },
  { text: "In der Stille spricht Gott.", author: "Mutter Teresa", category: "Stille" },
  { text: "Die schönsten Worte werden im Schweigen gesagt.", author: null, category: "Stille" },
  { text: "Die größten Ereignisse — das sind nicht unsere lautesten, sondern unsere stillsten Stunden.", author: "Friedrich Nietzsche", category: "Stille" },
  { text: "Manches lernt man nur, wenn man leise wird.", author: null, category: "Stille" },
  { text: "Es gibt Augenblicke, in denen man über Jahre nachdenken kann.", author: "Edith Wharton", category: "Stille" },
  { text: "Je leiser du wirst, desto mehr kannst du hören.", author: "Rumi", category: "Stille" },
  { text: "Wer sich selbst nicht aushält, kann die Stille nicht aushalten.", author: null, category: "Stille" },
  { text: "Zuhören ist schwerer als reden, weil zuhören die ganze Welt aufnimmt, während Reden nur deine eigene hinaus trägt.", author: null, category: "Stille" },
  { text: "Weisheit beginnt im Schweigen.", author: null, category: "Stille" },
  { text: "Wer zu schnell spricht, denkt selten nach.", author: null, category: "Stille" },
  { text: "Der Raum zwischen den Worten ist wichtiger als die Worte selbst.", author: null, category: "Stille" },
  { text: "Nichts-Tun ist auch eine Entscheidung.", author: null, category: "Stille" },

  // ---------- Metaphern (13) ----------
  { text: "Das Leben ist wie ein Fahrrad. Man muss sich vorwärts bewegen, um das Gleichgewicht nicht zu verlieren.", author: "Albert Einstein", category: "Metaphern" },
  { text: "Der einzige Mensch, der sich vernünftig benimmt, ist mein Schneider. Er nimmt jedesmal neu Maß, wenn er mich trifft, während alle anderen immer die alten Maßstäbe anlegen in der Meinung, sie passten auch heute noch.", author: "George Bernard Shaw", category: "Metaphern" },
  { text: "Die Wunde ist der Ort, durch den das Licht in dich eintritt.", author: "Rumi", category: "Metaphern" },
  { text: "Das Herz hat seine Gründe, die der Verstand nicht kennt.", author: "Blaise Pascal", category: "Metaphern" },
  { text: "Niemand steigt zweimal in denselben Fluss.", author: "Heraklit", category: "Metaphern" },
  { text: "Der Weg ist das Ziel.", author: "Konfuzius", category: "Metaphern" },
  { text: "Wir sind nicht, was uns passiert ist. Wir sind, was wir daraus gemacht haben.", author: "C. G. Jung", category: "Metaphern" },
  { text: "Die Hölle, das sind die anderen.", author: "Jean-Paul Sartre", category: "Metaphern" },
  { text: "Wenn du etwas findest, das größer ist als deine Angst, nennst du es Berufung.", author: null, category: "Metaphern" },
  { text: "Das Leben gewinnt seine Bedeutung nicht dadurch, dass wir es verstehen, sondern dadurch, dass wir es leben.", author: null, category: "Metaphern" },
  { text: "Das Leben ist ein Echo. Was du aussendest, kommt zurück.", author: null, category: "Metaphern" },
  { text: "Das Leben ist wie ein Buch mit vielen Kapiteln. Manche gut, manche traurig, manche zum Weinen. Aber wenn du niemals eine Seite umschlägst, wirst du nie wissen, was das nächste Kapitel bringt.", author: null, category: "Metaphern" },
  { text: "Nicht alle, die umherwandern, sind verloren.", author: "J. R. R. Tolkien", category: "Metaphern" },

  // ---------- Richtung (17) ----------
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain", category: "Richtung" },
  { text: "Wir dürfen niemals vergessen: Unsere vornehmste Aufgabe ist es zu leben.", author: "Michel de Montaigne", category: "Richtung" },
  { text: "Es ist kein Zeichen geistiger Gesundheit, gut angepasst an eine kranke Gesellschaft zu sein.", author: "Jiddu Krishnamurti", category: "Richtung" },
  { text: "Du kannst keine neuen Ozeane entdecken, wenn du dich nicht traust, das Ufer aus den Augen zu verlieren.", author: "André Gide", category: "Richtung" },
  { text: "Niemand hätte jemals das Meer überquert, wenn er die Möglichkeit gehabt hätte, bei Sturm das Schiff zu verlassen.", author: "Charles F. Kettering", category: "Richtung" },
  { text: "Wer das Warum kennt, erträgt fast jedes Wie.", author: "Friedrich Nietzsche", category: "Richtung" },
  { text: "Die Frage ist nicht, wer mich gehen lässt. Die Frage ist, wer mich nicht aufhält.", author: "Ayn Rand", category: "Richtung" },
  { text: "Ich bin nicht auf dieser Welt, um zu sein, wie andere mich haben wollen.", author: "Fritz Perls", category: "Richtung" },
  { text: "Ohne eine Vision bist du nur ein Sklave für die, die eine haben.", author: "The Grim", category: "Richtung" },
  { text: "Es ist nie zu spät, der zu sein, der du hättest sein können.", author: "George Eliot", category: "Richtung" },
  { text: "Die Welt tritt zur Seite, um den Menschen passieren zu lassen, der weiß, wohin er geht.", author: "Ralph Waldo Emerson", category: "Richtung" },
  { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln", category: "Richtung" },
  { text: "Wer Veränderungen herbeiführen möchte, aber selber nichts dafür tut, ist wie ein Mensch, der am Bahnhof steht und auf eine Fähre wartet.", author: null, category: "Richtung" },
  { text: "Wer sein Leben kennt, stirbt glücklich.", author: null, category: "Richtung" },
  { text: "Das Leben ist, was dir passiert, während du damit beschäftigt bist, andere Pläne zu machen.", author: "John Lennon", category: "Richtung" },
  { text: "Wer nicht weiß, wohin er segeln will, für den ist kein Wind der richtige.", author: "Seneca", category: "Richtung" },
  { text: "Das Ziel ist nicht, ins Paradies zu kommen. Das Ziel ist, das Paradies ins Hier zu bringen.", author: null, category: "Richtung" },
  { text: "Where your focus goes, energy flows.", author: null, category: "Richtung" },
  { text: "Alles wird sich fügen, wenn ich abwarte. Ohne Entscheidung bleibt alles offen — und genau das macht müde.", author: null, category: "Richtung" },

  // ---------- Resilienz (15) ----------
  { text: "You can't stop the waves, but you can learn to surf.", author: "Jon Kabat-Zinn", category: "Resilienz" },
  { text: "Wer um Regen betet, sollte auf den Schlamm gefasst sein.", author: "Indisches Sprichwort", category: "Resilienz" },
  { text: "Es sind nicht die Dinge, die uns beunruhigen, sondern unsere Meinungen über die Dinge.", author: "Epiktet", category: "Resilienz" },
  { text: "Während wir auf das Leben warten, vergeht es.", author: "Seneca", category: "Resilienz" },
  { text: "Wer mit Ungeheuern kämpft, mag zusehen, dass er nicht dabei zum Ungeheuer wird.", author: "Friedrich Nietzsche", category: "Resilienz" },
  { text: "Fast alles funktioniert wieder, wenn du es für ein paar Minuten ausstöpselst — auch du.", author: "Anne Lamott", category: "Resilienz" },
  { text: "Das Gegenteil von Mut ist nicht Feigheit, sondern Konformität.", author: "Rollo May", category: "Resilienz" },
  { text: "Wenn du durch die Hölle gehst, geh weiter.", author: "Winston Churchill", category: "Resilienz" },
  { text: "Das Leben ist zu kurz, um es schlecht zu leben.", author: "Johann Wolfgang von Goethe", category: "Resilienz" },
  { text: "Verletzlichkeit ist keine Schwäche. Sie ist unsere größte Stärke.", author: "Brené Brown", category: "Resilienz" },
  { text: "Was uns nicht umbringt, macht uns stärker.", author: "Friedrich Nietzsche", category: "Resilienz" },
  { text: "Tränen sind Worte, die das Herz nicht sagen kann.", author: null, category: "Resilienz" },
  { text: "Alles hat eine Bedeutung — auch das, was keine zu haben scheint.", author: null, category: "Resilienz" },
  { text: "Schmerz ist unvermeidlich. Leiden ist optional.", author: "Haruki Murakami", category: "Resilienz" },
  { text: "Manchmal muss man den Sturm überstehen, um zu erkennen, wie stark man ist.", author: null, category: "Resilienz" },

  // ---------- Schönheit (15) ----------
  { text: "Beautiful people are not always good but good people are always beautiful.", author: "Alī ibn Abī Tālib", category: "Schönheit" },
  { text: "Never let the sadness of your past and the fear of your future ruin the happiness of your present.", author: null, category: "Schönheit" },
  { text: "Öffne deine Augen und du entdeckst im Alltäglichen das Wunderbare.", author: null, category: "Schönheit" },
  { text: "Die Menschen sind wie bunte Glasfenster: Sie funkeln und leuchten, wenn die Sonne scheint; doch nach Anbruch der Dunkelheit wird ihre wahre Schönheit nur offenbar, wenn sie ein inneres Licht haben.", author: "Elisabeth Kübler-Ross", category: "Schönheit" },
  { text: "Schönheit wird die Welt retten.", author: "Fjodor Dostojewski", category: "Schönheit" },
  { text: "Dinge bewundern ist eine Form der Liebe.", author: "Frank Ostaseski", category: "Schönheit" },
  { text: "Die wahre Schönheit eines Menschen liegt darin, wie er andere behandelt.", author: null, category: "Schönheit" },
  { text: "Alles hat Schönheit, aber nicht jeder sieht sie.", author: "Konfuzius", category: "Schönheit" },
  { text: "Schönheit beginnt in dem Moment, in dem du dich entscheidest, du selbst zu sein.", author: "Coco Chanel", category: "Schönheit" },
  { text: "Es gibt keinen Fahrplan durch die Menschwerdung, nur Wegweiser. Und manchmal sehen sie aus wie andere Menschen.", author: null, category: "Schönheit" },
  { text: "Das Leben ist hart. Du selbst musst es sanft machen.", author: null, category: "Schönheit" },
  { text: "Manchmal genügt ein Augenblick, um das ganze Leben zu verändern.", author: null, category: "Schönheit" },
  { text: "Das Beste an schönen Menschen ist, wie sie andere schön machen.", author: null, category: "Schönheit" },
  { text: "Es gibt keine Schönheit ohne Maß.", author: "Andrea Palladio", category: "Schönheit" },
  { text: "Schöner ist nichts, als was der Mensch werden kann.", author: null, category: "Schönheit" },

  // ---------- Neuanfang (13) ----------
  { text: "Nach meiner Meinung ist es nie zu spät oder in meinem Fall zu früh, der zu sein, der man sein will. Es gibt keine zeitliche Begrenzung. Fang damit an, wann du willst. Du kannst dich ändern oder so bleiben wie du bist. Es gibt keine Regel. Du kannst das Beste daraus machen oder das Schlechteste. Ich hoffe, du machst das Beste daraus.", author: "Benjamin Button", category: "Neuanfang" },
  { text: "Jedem Anfang wohnt ein Zauber inne.", author: "Hermann Hesse", category: "Neuanfang" },
  { text: "Wo du nicht bist, da ist das Glück.", author: "Franz Schubert", category: "Neuanfang" },
  { text: "Es gibt keine Rettung — es gibt nur das Weitergehen.", author: null, category: "Neuanfang" },
  { text: "Die Vergangenheit ist nicht, was war. Sie ist, was du heute aus ihr machst.", author: null, category: "Neuanfang" },
  { text: "Wer neu anfangen will, muss loslassen, was er weiß.", author: null, category: "Neuanfang" },
  { text: "Der beste Zeitpunkt, einen Baum zu pflanzen, war vor zwanzig Jahren. Der zweitbeste ist jetzt.", author: "Chinesisches Sprichwort", category: "Neuanfang" },
  { text: "Manchmal musst du dich selbst auseinander nehmen, um wieder ganz zu werden.", author: null, category: "Neuanfang" },
  { text: "Auferstehung ist kein Ereignis. Es ist eine Praxis.", author: null, category: "Neuanfang" },
  { text: "Ich habe mich eines Tages verloren — und bin als ein Anderer wiedergekommen.", author: null, category: "Neuanfang" },
  { text: "Ich habe keine Ahnung, wohin ich gehe, aber ich bin auf dem Weg.", author: "Carl Sandburg", category: "Neuanfang" },
  { text: "Jeden Morgen sind wir neu geboren. Was wir heute tun, zählt am meisten.", author: "Buddha", category: "Neuanfang" },
  { text: "Wer nicht verliert, hat nie wirklich gespielt.", author: null, category: "Neuanfang" },

  // ---------- Zeit (14) ----------
  { text: "Die Zeiten, die zählen, sind die Zeiten, die nicht gezählt werden.", author: null, category: "Zeit" },
  { text: "Das Leben muss vorwärts gelebt, aber rückwärts verstanden werden.", author: "Søren Kierkegaard", category: "Zeit" },
  { text: "Nicht was wir erleben, sondern wie wir es empfinden, macht unser Schicksal aus.", author: "Marie von Ebner-Eschenbach", category: "Zeit" },
  { text: "Die meisten Menschen verschieben ihr Leben auf einen Tag, den sie Morgen nennen.", author: null, category: "Zeit" },
  { text: "Gestern ist Geschichte. Morgen ist ein Geheimnis. Heute ist ein Geschenk.", author: "Bil Keane", category: "Zeit" },
  { text: "Verschwende nicht den Rest deines Lebens mit Gedanken über andere.", author: "Marc Aurel", category: "Zeit" },
  { text: "Der gegenwärtige Augenblick ist der einzige, der uns zur Verfügung steht, und er ist die Tür zu allen anderen.", author: "Thich Nhat Hanh", category: "Zeit" },
  { text: "Das Leben ist kurz, aber breit.", author: null, category: "Zeit" },
  { text: "Wir haben nicht zu wenig Zeit, sondern zu viel Zeit, die wir nicht nutzen.", author: "Seneca", category: "Zeit" },
  { text: "Ein Tag gut gelebt ist ein ganzes Leben im Kleinen.", author: null, category: "Zeit" },
  { text: "Du kannst die Zeit nicht sparen. Du kannst sie nur verbringen — so oder anders.", author: null, category: "Zeit" },
  { text: "Zeit ist das, was wir am meisten wollen, aber am schlechtesten nutzen.", author: "William Penn", category: "Zeit" },
  { text: "Unsere Zeit ist begrenzt. Verschwendet sie also nicht, indem ihr das Leben eines anderen lebt.", author: "Steve Jobs", category: "Zeit" },
  { text: "Erinnerungen werden schöner, wenn man sie wiedersieht — nicht wenn man sie erlebt.", author: null, category: "Zeit" },

  // ---------- Einfachheit (16) ----------
  { text: "Alles sollte so einfach wie möglich gemacht werden, aber nicht einfacher.", author: "Albert Einstein", category: "Einfachheit" },
  { text: "Weniger ist mehr.", author: "Ludwig Mies van der Rohe", category: "Einfachheit" },
  { text: "Lächle, atme, gehe langsam.", author: "Thich Nhat Hanh", category: "Einfachheit" },
  { text: "Die höchste Form der Intelligenz ist die Einfachheit.", author: "Leonardo da Vinci", category: "Einfachheit" },
  { text: "Was man braucht, ist weniger. Was man wünscht, ist mehr. Was man hat, ist dazwischen.", author: null, category: "Einfachheit" },
  { text: "Glück ist nicht, alles zu haben, was man will, sondern zu wollen, was man hat.", author: null, category: "Einfachheit" },
  { text: "Wer viel hat, dem wird viel genommen.", author: null, category: "Einfachheit" },
  { text: "Halbe Wahrheiten sind oft die gefährlichsten Lügen.", author: "Alfred Tennyson", category: "Einfachheit" },
  { text: "Das Gute ist Feind des Besseren.", author: "Voltaire", category: "Einfachheit" },
  { text: "Manchmal ist das, was wir für ein Problem halten, eigentlich die Lösung.", author: null, category: "Einfachheit" },
  { text: "Wir sind Luftballons, voller Gefühle in einer Welt voller Nadeln.", author: null, category: "Einfachheit" },
  { text: "Alles ist Geschenk.", author: "Richard Rohr", category: "Einfachheit" },
  { text: "Die Seele ernährt sich von dem, worüber sie sich freut.", author: "Augustinus", category: "Einfachheit" },
  { text: "Man muss das Mögliche tun, damit das Unmögliche sichtbar wird.", author: null, category: "Einfachheit" },
  { text: "Man kann nur das behalten, was man geteilt hat.", author: null, category: "Einfachheit" },
  { text: "Alles, was ich über das Leben weiß, passt in einen einzigen Satz: Es geht weiter.", author: "Robert Frost", category: "Einfachheit" },
];

window.QUOTE_CATEGORIES = [...new Set(window.QUOTES.map(q => q.category))];